# Site settings
title: Frings's Blog
SEOTitle: Frings的博客 | Frings's Blog
header-img: img/post-desk.png #首页头顶的图片
email: 975634372@qq.com
description: "A new day,a nice start!."
keyword: " Frings's Blog , Frings的博客, Frings , lxy "
url: "http://Frings-Liu.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/Frings-Liu/Frings-Liu.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "huah emmmmmmmmmmmmmm!"
sidebar-avatar: /img/avatar_lxy.jpg     # 个人头像



# SNS settings
RSS: false
# weibo_username:     
zhihu_username:     
github_username:    Frings-Liu
facebook_username:  
#jianshu_username:   





# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus settings（https://disqus.com/）
disqus_username: Frings




# Analytics settings
# Baidu Analytics
ba_track_id: 61c59f039c9d1057dfb7fd724571adf7

# Google Analytics
ga_track_id: 'UA-110156152-1'            # Format: UA-xxxxxx-xx
ga_domain: auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "百度",
        href: "http://baidu.com"
    },{
        #title: "Apple",
        #href: "https://apple.com"
    },{
        #title: "Apple Developer",
        #href: "https://developer.apple.com/"
    }
]
